### ISSUE TITLE
Upgrade to Kotlin 1.4 as soon as it's out

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#41]
I experience on the `dev` branch NoSuchMethodErrors during Config Initializations when launching in IntelliJ. These are consistent with what is described in https://github.com/Kotlin/kotlinx.serialization/issues/576 and will be fixed in Kotlin 1.4 starting with 1.4-M3, see https://github.com/Kotlin/kotlinx.serialization/issues/378#issuecomment-663134060

**Comment by lucaro** [comment]
Kotlin 1.4 has been released: https://kotlinlang.org/docs/reference/whatsnew14.html

**Comment by gabuzi** [comment]
I actually upgraded to 1.4 "by accident" (upgraded the IntellJ plugin and now it only lets me compile in 1.4 due to changes with kotlinx-serialization).
There are a few changes necessary to make it run. I can compile without errors with https://github.com/vitrivr/cottontaildb/commit/80bfafe69ef15d6c486431aa06e8fce4947037d0.
